### REGISTER NEW USER
POST http://localhost:3001/api/register HTTP/1.1
Content-Type: application/json

{
    "name": "hi",
    "username": "slayer4000",
    "email": "will@gmail.com",
    "password": "asdfasdf"
}

### LOGIN WITH EMAIL
GET http://localhost:3001/api/login HTTP/1.1
Content-Type: application/json

{
    "account": "will@gmail.com",
    "password": "asdfasdf"
}

### LOGIN WITH USERNAME
GET http://localhost:3001/api/login HTTP/1.1
Content-Type: application/json

{
    "account": "slayer4000",
    "password": "asdfasdf"
}

### INVALID USER
GET http://localhost:3001/api/login HTTP/1.1
Content-Type: application/json

{
    "account": "slayer4a000",
    "password": "asdfasdf"
}

### WRONG PASSWORD
GET http://localhost:3001/api/login HTTP/1.1
Content-Type: application/json

{
    "account": "slayer4000",
    "password": "asdfaAsdf"
}

### UPDATE BIO
POST http://localhost:3001/api/bio HTTP/1.1
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7Il9pZCI6IjYwMGVmOTRlODMyOTI0MWQ3NGE3OGU1NyJ9LCJpYXQiOjE2MTE1OTg1NTIsImV4cCI6MTYxMjIwMzM1Mn0.HRead_VS9S4rD4ExFwA8E1M8BolYHQXTGWVeBJeukss
Content-Type: application/json

{
    "text": "ni xihuan chi pigu"
}